"""update user

Revision ID: 4c5380f78e5a
Revises: 30b50f8721ad
Create Date: 2024-04-21 00:47:59.066134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c5380f78e5a'
down_revision = '30b50f8721ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', sa.String(length=1024), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.drop_column('keywords')

    # ### end Alembic commands ###
