"""image

Revision ID: 65afdc45da84
Revises: 892a64334b72
Create Date: 2024-04-20 17:40:54.090039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65afdc45da84'
down_revision = '892a64334b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_b64', sa.String(length=100000), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
        batch_op.alter_column('company_size_lower',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('company_size_higher',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('company_size_higher',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('company_size_lower',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('image_b64')

    # ### end Alembic commands ###
