"""fix

Revision ID: 892a64334b72
Revises: 36ec882e802f
Create Date: 2024-04-20 17:27:46.714358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892a64334b72'
down_revision = '36ec882e802f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.alter_column('distance',
               existing_type=sa.TEXT(length=64),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.alter_column('distance',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
