"""initial

Revision ID: 8dbe6c209db3
Revises: 
Create Date: 2024-04-21 10:19:33.092410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dbe6c209db3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keyword_match', sa.Float(), nullable=False),
    sa.Column('summary', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('image_b64', sa.String(length=100000), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('company_size_lower', sa.Integer(), nullable=True),
    sa.Column('company_size_higher', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_company', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('education_text', sa.String(length=256), nullable=True),
    sa.Column('education_level', sa.Integer(), nullable=True),
    sa.Column('experience_text', sa.String(length=512), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('technologies_text', sa.String(length=512), nullable=True),
    sa.Column('soft_skills_text', sa.String(length=512), nullable=True),
    sa.Column('cv_filename', sa.String(length=64), nullable=True),
    sa.Column('cv_pdf_content', sa.LargeBinary(), nullable=True),
    sa.Column('profile_picture_bytes', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('job_posting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('salary_range_lower', sa.Integer(), nullable=False),
    sa.Column('salary_range_upper', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.String(length=1024), nullable=True),
    sa.Column('distance', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_interests',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_posting.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'job_posting_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_interests')
    op.drop_table('job_posting')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('company')
    op.drop_table('cache')
    # ### end Alembic commands ###
